avro_support_support_index:
    pattern:   /support
    defaults:  { _controller: AvroSupportBundle:Support:index }
avro_support_support_search:
    pattern:   /support/search
    defaults:  { _controller: AvroSupportBundle:Support:search }
avro_support_support_search_category:
    pattern:   /support/search/category/{id}
    defaults:  { _controller: AvroSupportBundle:Support:searchByCategory }
avro_support_support_search_user:
    pattern:   /support/search/user/{id}
    defaults:  { _controller: AvroSupportBundle:Support:searchByUser }

avro_support_support_sideWidget:
    pattern:   /support/sideWidget
    defaults:  { _controller: AvroSupportBundle:Support:sideWidget }

avro_support_question_list:
    pattern:   /support/questions/{filter}
    defaults:  { _controller: AvroSupportBundle:Question:list, filter: 'Open' }
avro_support_question_new:
    pattern:   /support/question/new/
    defaults:  { _controller: AvroSupportBundle:Question:new }
avro_support_question_show:
    pattern:   /support/question/show/{id}
    defaults:  { _controller: AvroSupportBundle:Question:show }
avro_support_question_edit:
    pattern:   /support/question/edit/{id}
    defaults:  { _controller: AvroSupportBundle:Question:edit }
avro_support_question_delete:
    pattern:   /support/question/delete/{id}
    defaults:  { _controller: AvroSupportBundle:Question:delete }
avro_support_question_close:
    pattern:   /support/question/close/{id}
    defaults:  { _controller: AvroSupportBundle:Question:close }
avro_support_question_open:
    pattern:   /support/question/open/{id}
    defaults:  { _controller: AvroSupportBundle:Question:open }
avro_support_question_addAnswer:
    pattern:   /support/question/addAnswer/{id}
    defaults:  { _controller: AvroSupportBundle:Question:addAnswer }
avro_support_question_deleteAnswer:
    pattern:   /support/question/deleteAnswer/{questionId}/{answerId}
    defaults:  { _controller: AvroSupportBundle:Question:deleteAnswer }

avro_support_category_list:
    pattern:   /support/categories
    defaults:  { _controller: AvroSupportBundle:Category:list }
avro_support_category_new:
    pattern:   /support/category/new
    defaults:  { _controller: AvroSupportBundle:Category:new }
avro_support_category_edit:
    pattern:   /support/category/edit/{id}
    defaults:  { _controller: AvroSupportBundle:Category:edit }
avro_support_category_delete:
    pattern:   /support/category/delete/{id}
    defaults:  { _controller: AvroSupportBundle:Category:delete }
